export const GET_LIST_TICKET_ROOM_REQUEST = 'GET_LIST_TICKET_ROOM_REQUEST';
export const GET_LIST_TICKET_ROOM_SUCCESS = 'GET_LIST_TICKET_ROOM_SUCCESS';
export const ADD_CHAIR_SUCCESS = 'ADD_CHAIR_SUCCESS';
