export const GET_PARENT_CINEMAS_REQUEST = 'GET_PARENT_CINEMAS_REQUEST';
export const GET_PARENT_CINEMAS_SUCCESS = 'GET_PARENT_CINEMAS_SUCCESS';
export const ADD_LIST_MOVIE_BY_PARENT_CINEMA = 'ADD_LIST_MOVIE_BY_PARENT_CINEMA';
export const GET_SHOWTIME_BY_PARENT_CINEMAS_REQUEST = 'GET_SHOWTIME_BY_PARENT_CINEMAS_REQUEST';
export const GET_SHOWTIME_BY_PARENT_CINEMAS_SUCCESS = 'GET_SHOWTIME_BY_PARENT_CINEMAS_SUCCESS';
export const ADD_LIST_MOVIE_BY_PARENT_CINEMA_ERROR = 'ADD_LIST_MOVIE_BY_PARENT_CINEMA_ERROR';

