export const GET_PARENT_CINEMAS_REQUEST = 'GET_PARENT_CINEMAS_REQUEST';
export const GET_PARENT_CINEMAS_SUCCESS = 'GET_PARENT_CINEMAS_SUCCESS';
export const GET_INFO_BY_PARENT_CINEMAS_REQUEST = 'GET_INFO_BY_PARENT_CINEMAS_REQUEST';
export const GET_INFO_BY_PARENT_CINEMAS_SUCCESS = 'GET_INFO_BY_PARENT_CINEMAS_SUCCESS';