export const GET_MOVIES_BY_DATE_REQUEST = 'GET_MOVIES_BY_DATE_REQUEST';
export const GET_MOVIES_BY_DATE_SUCCESS = 'GET_MOVIES_BY_DATE_SUCCESS';
export const GET_MOVIES_BY_DATE_FAILURE = 'GET_MOVIES_BY_DATE_FAILURE';
export const GET_MOVIES_LIST_REQUEST = 'GET_MOVIES_LIST_REQUEST';
export const GET_MOVIES_LIST_SUCCESS = 'GET_MOVIES_LIST_SUCCESS';
export const GET_MOVIES_LIST_FAILURE = 'GET_MOVIES_LIST_FAILURE';
export const GET_MOVIES_DETAIL_PAGE_REQUEST = 'GET_MOVIES_DETAIL_PAGE_REQUEST';
export const GET_MOVIES_DETAIL_PAGE_SUCCESS = 'GET_MOVIES_DETAIL_PAGE_SUCCESS';